### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jemole** [ucsb-cs-education/hairball-demo#1]
Hi, guys!

I have been trying to use your hairball demo (https://hairball.herokuapp.com/) but I always get the same error, no matter the project I upload: "upload complete: There was error running one of the plugins. Please report this issue."

So, I am reporting the issue :-)

Best regards,
J. Moreno.

**Comment by robmunoz** [comment]
:+1: here :(

**Comment by bboe** [comment]
@Garito and @robmunoz I am no longer working on this project. I know @jemole has done quite a bit of work with Hairball, so maybe he can offer a hand.

**Comment by jemole** [comment]
Yes, I'll try to look into it this week. In the meantime, people could analyze their Scratch projects with [Dr. Scratch](http://drscratch.org), which is implemented using Hairball plug-ins.

**Comment by bboe** [comment]
Thanks @jemole. Since Dr Scratch should work, I'm going to essentially put this repository in READONLY mode and refer people to it.
